debug: true
build:
  image: golang
  commands:
    - go get
    - go build
    - go test
publish:
docker:
  registry: quay.io
  username: $$QUAY_USERNAME
  password: $$QUAY_PASSWORD
  email: richard@jentzsch.me
  repo: norbell/dronetest
  file: Dockerfile